### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by GuillaumeCisco** [Substra/substra-backend#411]
Is this project dead?

**Comment by AurelienGasser** [comment]
Hi @GuillaumeCisco, 

Thanks for your interest in the project's progress. 

At this point, substra-backend is inactive as an open-source project. However, the Substra project is under active development as a closed-source solution. There are ongoing strategic discussions regarding the possibility of open-sourcing newer versions, but no conclusion has been reached yet.

The repo's README has been updated to reflect the current situation https://github.com/Substra/substra-backend#readme
