### ISSUE TITLE
which backend url do I use to instantiate a Client?

### ISSUE THREAD

**Issue by bhomass** [Substra/substra-backend#584]
I made Test locally - dev setup. The backend pos/containers show up as
default         service/backend-org-1-substra-backend-server   ClusterIP   10.43.81.5      <none>        8000/TCP                     4d20h
org-1           service/backend-org-1-substra-backend-server   ClusterIP   10.43.38.214    <none>        8000/TCP                     4d20h

in a local ipynb file, I tried both ip's like client = substra.Client(url="https://10.43.38.214:8000") and 
client.login(username="org-1", password="p@sswr0d44")

it hangs and times out. Just which ip would work?

**Comment by oleobal** [comment]
The IPs you are referring to are internal to the cluster; if you have followed the dev setup, the backend service is exposed to `substra-backend.org-1.com:8000`, so connecting to that should work.

You can read more about Kubernetes networking [here](https://kubernetes.io/docs/concepts/services-networking/) if you are interested.

Please use [Slack](substra-workspace.slack.com) for usage questions and use GitHub issues only for bug reports in the future :)
